export const colors = {
  primary: '#000000',
  onPrimary: '#ffffff',
  background: '#ffffff',
  onBackground: '#000000',
  secondary: '#000000',
  onSecondary: '#eee',
  secondaryContainer: '#eee',
  onSecondaryContainer: '#000000',
  surface: '#efefef',
  onSurface: '#000000',
  surfaceVariant: '#eeeeee',
  onSurfaceVariant: '#000000',
  inverseSurface: '#111111',
  inverseOnSurface: '#eeeeee',
  inversePrimary: '#eeeeee',
} as const;
